<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="James Doss-Gollin" />

<meta name="date" content="2016-06-28" />

<title>Getting Started with cpcRain</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>



<link href="data:text/css;charset=utf-8,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23header%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%20code%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" rel="stylesheet" type="text/css" />

</head>

<body>




<h1 class="title toc-ignore">Getting Started with cpcRain</h1>
<h4 class="author"><em>James Doss-Gollin</em></h4>
<h4 class="date"><em>2016-06-28</em></h4>



<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr::opts_chunk$<span class="kw">set</span>(<span class="dt">warnings =</span> F, <span class="dt">message =</span> F)</code></pre></div>
<div id="motivation" class="section level1">
<h1>Motivation</h1>
<p>This package is an extension and overhaul of the original <a href="https://github.com/dlebauer/cpcRain">cpcRain package</a> by <a href="https://github.com/dlebauer">dlebauer</a>. Many of the functions were written by Gopi Goteti in their first form and I have just updated and extended them. That package presented R code to download and analyze global precipitation data from the Climate Prediction Center (CPC)</p>
<ul>
<li>Spatial Coverage: Global (mostly land areas)</li>
<li>Temporal Coverage: 1979 - present</li>
<li>Spatial Resolution: 0.5 degrees lat-lon</li>
<li>Temporal Resolution: daily</li>
</ul>
<p>Hydrological and climatological studies sometimes require rainfall data over the entire world for long periods of time. The Climate Prediction Center’s <a href="http://www.cpc.ncep.noaa.gov/">(CPC)</a> daily data, from 1979 to present, at a spatial resolution of 0.5 degrees lat-lon (~ 50 km at the equator) is a good resource. This data is available at CPC’s ftp site (<a href="ftp://ftp.cpc.ncep.noaa.gov/precip/CPC_UNI_PRCP/GAUGE_GLB/" class="uri">ftp://ftp.cpc.ncep.noaa.gov/precip/CPC_UNI_PRCP/GAUGE_GLB/</a>). However, there are a number of issues:</p>
<p>Issues with obtaining data:</p>
<ul>
<li>there are too many files (365/366 per year * 34 years, separate folder for each year)</li>
<li>file naming conventions have chnaged over time, one format prior to 2006 and couple of different formats afterwards</li>
<li>downloading multiple files simultaneously from the CPC ftp site does not seem to work properly.</li>
</ul>
<p>Issues with processing data:</p>
<ul>
<li>file formats have changed over time, gzipped files prior to 2008 and binary files afterwards</li>
<li>files are in binary format and there no software/code readily available to process/plot the data</li>
</ul>
</div>
<div id="package-philosophy" class="section level1">
<h1>Package Philosophy</h1>
<p>This package is designed to facilitate two use cases that are likely to cover most users of the CPC data:</p>
<ol style="list-style-type: decimal">
<li>Users who wish to extract data from a single date or a short date range for one-time use. This is possible through the <code>cpcQueryDateRange</code> function.</li>
<li>Users who wish to build a library of CPC data which they can query whenever is needed. This is accomplished by two functions. First the <code>cpcYearToNCDF</code> function downloads all CPC data (one year at a time) and stores the full year of data to a compressed NCDF (version 4) file. Next the <code>cpcReadNCDF</code> function allows users to easily extract data from those files. Extracting data from multiple years at once is permitted, as long as the data files for all years are present.</li>
</ol>
<p>Further, this package supports users who wish to extract data in two formats: 1. 3D arrays. The CPC data is gridded on a 0.5 degree grid of longitude and latitude; the third dimension is time. 2. Tidy data, via the <code>data.table</code> package. This format allows for easy manipulation of multiple variables, subsetting, grouping, and other fast operations on the data.</p>
<div id="installation" class="section level2">
<h2>Installation</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">if(!<span class="kw">require</span>(<span class="st">'devtools'</span>)) <span class="kw">install.packages</span>(<span class="st">'devtools'</span>)
devtools::<span class="kw">install_github</span>(<span class="st">'jdossgollin/cpcRain'</span>, <span class="dt">dependencies =</span> T)
<span class="kw">library</span>(cpcRain)</code></pre></div>
</div>
<div id="accessing-this-document" class="section level2">
<h2>Accessing This Document</h2>
<p>You can read this vignette at any time from your <strong>R</strong> session by calling:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">vignette</span>(<span class="st">'Introduction'</span>, <span class="dt">package =</span> <span class="st">'cpcRain'</span>)</code></pre></div>
<pre><code>## Warning: vignette 'Introduction' not found</code></pre>
</div>
</div>
<div id="example-1-sending-a-quick-data-query" class="section level1">
<h1>Example 1: Sending a Quick Data Query</h1>
<p>For this example, we’ll download data from the winter holidays of 1998. Since we’re just interested in a short date range, we don’t need to download years of data, write <code>.nc</code> files, or construct complicated databases. We do this with the <code>cpcQueryDateRange</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dt1 &lt;-<span class="st"> </span><span class="kw">cpcQueryDateRange</span>(<span class="dt">start_date =</span> <span class="kw">ymd</span>(<span class="st">'1998-12-24'</span>),
                         <span class="dt">end_date =</span> <span class="kw">ymd</span>(<span class="st">'1999-01-04'</span>),
                         <span class="dt">tidy =</span> T)</code></pre></div>
<p>We’ll look into the <code>tidy</code> argument in a moment. The <code>cpcQueryDateRange</code> gives us a list of outputs. The first tells us whether the dates we requested were successfully downloaded:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dt1$download_success</code></pre></div>
<pre><code>##          date success
## 1  1998-12-24    TRUE
## 2  1998-12-25    TRUE
## 3  1998-12-26    TRUE
## 4  1998-12-27    TRUE
## 5  1998-12-28    TRUE
## 6  1998-12-29    TRUE
## 7  1998-12-30    TRUE
## 8  1998-12-31    TRUE
## 9  1999-01-01    TRUE
## 10 1999-01-02    TRUE
## 11 1999-01-03    TRUE
## 12 1999-01-04    TRUE</code></pre>
<p>The second gives the rainfall data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dt1$precip_data</code></pre></div>
<pre><code>##                date    lon    lat prcp_mm
##       1: 1998-12-24   0.25 -89.75       0
##       2: 1998-12-24   0.75 -89.75       0
##       3: 1998-12-24   1.25 -89.75       0
##       4: 1998-12-24   1.75 -89.75       0
##       5: 1998-12-24   2.25 -89.75       0
##      ---                                 
## 3110396: 1999-01-04 357.75  89.75      NA
## 3110397: 1999-01-04 358.25  89.75      NA
## 3110398: 1999-01-04 358.75  89.75      NA
## 3110399: 1999-01-04 359.25  89.75      NA
## 3110400: 1999-01-04 359.75  89.75      NA</code></pre>
<p>Since we set <code>tidy = TRUE</code>, we get a tidy <code>data.table</code>. If you’re not familiar with this package and data format, you should read their introductions (on the CRAN package page, for example). The <code>data.table</code> syntax allows us to subset, group, and apply functions to the data easily. We can also <em>cast</em> our data to create a matrix of dates versus grid cells using the <code>data.table::dcast</code> function.</p>
<p>We can also set <code>tidy = FALSE</code> to get an array of the data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dt2 &lt;-<span class="st"> </span><span class="kw">cpcQueryDateRange</span>(<span class="dt">start_date =</span> <span class="kw">ymd</span>(<span class="st">'1998-12-24'</span>),
                         <span class="dt">end_date =</span> <span class="kw">ymd</span>(<span class="st">'1999-01-04'</span>),
                         <span class="dt">tidy =</span> F)</code></pre></div>
<p>Be aware that every time you use the <code>cpcQueryDateRange</code> function, data is re-downloaded from the server.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dt2$precip_data %&gt;%<span class="st"> </span><span class="kw">dim</span>()</code></pre></div>
<pre><code>## [1] 720 360  12</code></pre>
<p>As expected, our data has 720 values of longitude, 360 of latitude, and 12 of time. The <code>dimnames</code> gives us the longitude, latitude, and date parameters in an easy-to-parse format:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lapply</span>(<span class="kw">dimnames</span>(dt2$precip_data), head)</code></pre></div>
<pre><code>## [[1]]
## [1] &quot;0.25&quot; &quot;0.75&quot; &quot;1.25&quot; &quot;1.75&quot; &quot;2.25&quot; &quot;2.75&quot;
## 
## [[2]]
## [1] &quot;-89.75&quot; &quot;-89.25&quot; &quot;-88.75&quot; &quot;-88.25&quot; &quot;-87.75&quot; &quot;-87.25&quot;
## 
## [[3]]
## [1] &quot;1998-12-24&quot; &quot;1998-12-25&quot; &quot;1998-12-26&quot; &quot;1998-12-27&quot; &quot;1998-12-28&quot;
## [6] &quot;1998-12-29&quot;</code></pre>
<p>If we want, we can use the <code>cpcMeltArray</code> function to turn the 3D array of <code>dt2$precip_data</code> into the <code>data.table</code> of <code>dt1$precip_data</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dt3 &lt;-<span class="st"> </span>dt2$precip_data %&gt;%<span class="st"> </span>cpcMeltArray
<span class="kw">colMeans</span>(dt3 ==<span class="st"> </span>dt1$precip_data, <span class="dt">na.rm =</span> T)</code></pre></div>
<pre><code>##    date     lon     lat prcp_mm 
##       1       1       1       1</code></pre>
<p>This shows that we get the same results either way.</p>
</div>
<div id="example-2-building-a-data-library" class="section level1">
<h1>Example 2: Building a Data Library</h1>
<p>Now let’s imagine that we’re not content just querying data from a few weeks, but we want to look at all rainfall over the Northeast United States from 1997-2000. Since this will be a large data set, we’re going to use the <code>cpcYearToNCDF</code> function to build a library of <code>.nc</code> files, one for each year, to store our data. That way, we can access it efficiently whenever we want.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">download_years &lt;-<span class="st"> </span><span class="dv">1979</span>:<span class="dv">2016</span>
success &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">'list'</span>, <span class="kw">length</span>(download_years))
for(i in <span class="dv">1</span>:<span class="kw">length</span>(download_years)){
  success[[i]] &lt;-<span class="st"> </span><span class="kw">cpcYearToNCDF</span>(
    <span class="dt">year =</span> download_years[i],
    <span class="dt">download_folder =</span> <span class="st">'~/Documents/Data/CPC/'</span>,
    <span class="dt">empty_raw =</span> <span class="ot">TRUE</span>,
    <span class="dt">overwrite =</span> <span class="ot">FALSE</span>
  )
}
success &lt;-<span class="st"> </span><span class="kw">rbindlist</span>(success)</code></pre></div>
<p>The <code>download_folder</code> parameter specifies where we want to save our <code>.nc</code> files after we create them. The <code>empty_raw</code> is set to TRUE, so the program will automatically delete the raw files downloaded from the CPC server after the <code>.nc</code> file is successfully created. Finally, the <code>overwrite</code> parameter is FALSE, so for a given year if the <code>.nc</code> file already exists then the function won’t download the data and write the data.</p>
<p>We can check the success of the data download:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">success[<span class="kw">order</span>(success, date)]</code></pre></div>
<pre><code>##              date success
##     1: 1979-01-01    TRUE
##     2: 1979-01-02    TRUE
##     3: 1979-01-03    TRUE
##     4: 1979-01-04    TRUE
##     5: 1979-01-05    TRUE
##    ---                   
## 13876: 2016-12-27    TRUE
## 13877: 2016-12-28    TRUE
## 13878: 2016-12-29    TRUE
## 13879: 2016-12-30    TRUE
## 13880: 2016-12-31    TRUE</code></pre>
<p>If it shows up as “Not Attempted”, it’s because the <code>.nc</code> file was already downloaded and <code>overwrite</code> was set to FALSE. The process of downloading the files and creating the <code>.nc</code> files is slow, but once they’re there, it’s very easy to query them. You don’t even need to do it from <strong>R</strong> – any software package that can read NCDF <em>version 4</em> files can read them. One way to read the files is with the excellent <code>ncdf4</code> package like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nc &lt;-<span class="st"> </span><span class="kw">nc_open</span>(<span class="st">&quot;~/Documents/Data/CPC/cpcRain_1997.nc&quot;</span>)</code></pre></div>
<p>You’ll notice that the units on the <code>time</code> variable are a bit odd:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nc$dim$time$vals[<span class="dv">1</span>:<span class="dv">10</span>]</code></pre></div>
<pre><code>##  [1] 9862 9863 9864 9865 9866 9867 9868 9869 9870 9871</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nc$dim$time$units</code></pre></div>
<pre><code>## [1] &quot;days since 1970-01-01&quot;</code></pre>
<p>However, the advantage here is that the <code>lubridate</code> package’s <code>as_date</code> function takes the origin to be 1970-01-01 by default, so you can call <code>as_date(nc$dim$time$vals)</code> without any trouble.</p>
<p>Still, this is a needlessly complicated way to extract data from these files. You don’t even have to call . The much easier way is to use the <code>cpcReadNCDF</code> function, which can extract data from multiple years at once. Since the <code>.nc</code> files are gridded by default, we can subset the data before reading it in:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dt4 &lt;-<span class="st"> </span><span class="kw">cpcReadNCDF</span>(
  <span class="dt">start_date =</span> <span class="kw">ymd</span>(<span class="st">'1997-12-01'</span>),
  <span class="dt">end_date =</span> <span class="kw">ymd</span>(<span class="st">'1999-02-11'</span>),
  <span class="dt">lat_lims =</span> <span class="kw">c</span>(<span class="dv">35</span>, <span class="dv">45</span>),
  <span class="dt">lon_lims =</span> <span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">110</span>),
  <span class="dt">download_folder =</span> <span class="st">'~/Documents/Data/CPC/'</span>,
  <span class="dt">tidy =</span> <span class="ot">TRUE</span>,
  <span class="dt">round_lonlat =</span> <span class="ot">TRUE</span>
)</code></pre></div>
<pre><code>## Warning in cpcReadNCDF(start_date = ymd(&quot;1997-12-01&quot;), end_date =
## ymd(&quot;1999-02-11&quot;), : Adjusting lat_lims to nearest grid point</code></pre>
<pre><code>## Warning in cpcReadNCDF(start_date = ymd(&quot;1997-12-01&quot;), end_date =
## ymd(&quot;1999-02-11&quot;), : Adjusting lon_lims to nearest grid point</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(dt4)</code></pre></div>
<pre><code>##               date    lon   lat    prcp_mm
##      1: 1997-12-01  99.75 34.75 0.87346697
##      2: 1997-12-01 100.25 34.75 0.65020645
##      3: 1997-12-01 100.75 34.75 0.40431538
##      4: 1997-12-01 101.25 34.75 0.20078394
##      5: 1997-12-01 101.75 34.75 0.07473714
##     ---                                   
## 193154: 1999-02-11 107.75 44.75 0.00000000
## 193155: 1999-02-11 108.25 44.75 0.00000000
## 193156: 1999-02-11 108.75 44.75 0.00000000
## 193157: 1999-02-11 109.25 44.75 0.00000000
## 193158: 1999-02-11 109.75 44.75 0.00000000</code></pre>
<p>The <code>start_date</code>, <code>end_date</code>, <code>lat_lims</code>, and <code>lon_lims</code> parameters are pretty straightforward and do exactly what you would imagine. The <code>download_folder</code> needs to be where the <code>.nc</code> files are stored – this will be the same as the argument to the <code>cpcYearToNCDF</code> function. The <code>tidy</code> argument, like before, causes the function to return a <code>data.table</code> if TRUE and a 3D array if FALSE. The array can, again, be melted with <code>cpcMeltArray</code>. Finally, the <code>round_lonlat</code> argument is set to TRUE. Under the hood, the function automatically rounded the <code>lat_lims</code> and <code>lon_lims</code> slightly to give results that fit within the data. If <code>round_lonlat</code> is FALSE, then entering values that aren’t in the data set will throw an error.</p>
</div>
<div id="improvements" class="section level1">
<h1>Improvements</h1>
<p>This is a brand new version of this package, so there are likely to be bugs. Please use the issues tracker at <a href="https://github.com/jdossgollin/cpcRain/issues" class="uri">https://github.com/jdossgollin/cpcRain/issues</a> to report issues, bugs, improvements, bad documentation, etc. Thanks in advance for your help!</p>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
